INSERT INTO CUSTOMER(CUSTOMER_FIRST_NAME, CUSTOMER_LAST_NAME) VALUES('Gerald', 'McClellan');
INSERT INTO CUSTOMER(CUSTOMER_FIRST_NAME, CUSTOMER_LAST_NAME) VALUES('Joe', 'Frazier');
INSERT INTO CUSTOMER(CUSTOMER_FIRST_NAME, CUSTOMER_LAST_NAME) VALUES('Orlando', 'Canizales');
INSERT INTO CUSTOMER(CUSTOMER_FIRST_NAME, CUSTOMER_LAST_NAME) VALUES('Julian', 'Jackson');
INSERT INTO CUSTOMER(CUSTOMER_FIRST_NAME, CUSTOMER_LAST_NAME) VALUES('Ray', 'Leonard');
INSERT INTO CUSTOMER(CUSTOMER_FIRST_NAME, CUSTOMER_LAST_NAME) VALUES('Tommy', 'Hearns');
INSERT INTO CUSTOMER(CUSTOMER_FIRST_NAME, CUSTOMER_LAST_NAME) VALUES('Roberto', 'Duran');
INSERT INTO CUSTOMER(CUSTOMER_FIRST_NAME, CUSTOMER_LAST_NAME) VALUES('Marvin', 'Hagler');
INSERT INTO CUSTOMER(CUSTOMER_FIRST_NAME, CUSTOMER_LAST_NAME) VALUES('Mike', 'McCallum');
INSERT INTO CUSTOMER(CUSTOMER_FIRST_NAME, CUSTOMER_LAST_NAME) VALUES('James', 'Toney');

INSERT INTO MANUFACTURER(MANUFACTURER_NAME) VALUES('Spacely Sprockets');
INSERT INTO MANUFACTURER(MANUFACTURER_NAME) VALUES('Haberdash Hammers');
INSERT INTO MANUFACTURER(MANUFACTURER_NAME) VALUES('Scrabble Screwdrivers');
INSERT INTO MANUFACTURER(MANUFACTURER_NAME) VALUES('Nashville Nails');
INSERT INTO MANUFACTURER(MANUFACTURER_NAME) VALUES('Bowling Bolts');

INSERT INTO PRODUCT(MANUFACTURER_ID, PRODUCT_NAME) VALUES(1, 'Sprocket');
INSERT INTO PRODUCT(MANUFACTURER_ID, PRODUCT_NAME) VALUES(2, 'Hammer');
INSERT INTO PRODUCT(MANUFACTURER_ID, PRODUCT_NAME) VALUES(2, 'Mallet');
INSERT INTO PRODUCT(MANUFACTURER_ID, PRODUCT_NAME) VALUES(3, 'Screwdriver');
INSERT INTO PRODUCT(MANUFACTURER_ID, PRODUCT_NAME) VALUES(3, 'Screw');
INSERT INTO PRODUCT(MANUFACTURER_ID, PRODUCT_NAME) VALUES(4, 'Nail');
INSERT INTO PRODUCT(MANUFACTURER_ID, PRODUCT_NAME) VALUES(5, 'Bolt');
INSERT INTO PRODUCT(MANUFACTURER_ID, PRODUCT_NAME) VALUES(5, 'Nut');

